### ISSUE TITLE
Error on ./iSniff_import.py -i wlan1

### ISSUE THREAD

**Issue by tailer73** [hubert3/iSniff-GPS#22]
Hi!
Start import wifi network and get error:

./iSniff_import.py -i wlan1
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "./iSniff_import.py", line 10, in <module>
    from iSniff_GPS.models import Client, AP, Location
  File "/root/iSniff-GPS/iSniff_GPS/models.py", line 5, in <module>
    class Client(models.Model):
  File "/root/iSniff-GPS/iSniff_GPS/models.py", line 6, in Client
    mac = models.CharField(max_length=len('ff:ff:ff:ff:ff:ff'), unique=True) 
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 1012, in __init__
    super(CharField, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/fields/__init__.py", line 146, in __init__
    self.db_tablespace = db_tablespace or settings.DEFAULT_INDEX_TABLESPACE
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 40, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting DEFAULT_INDEX_TABLESPACE, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

Please, help me solve this problem.

**Comment by hubert3** [comment]
Hi, did you follow the instructions in README.md?

Specifically the 3 steps under "To use the web interface" (you need to do this first to create the database) then the 4 steps under "To sniff wifi traffic". I would recommend that you use run.sh rather than calling iSniff_import.py directly.

**Comment by tailer73** [comment]
Yes, i am follow your instruction in README.md.
Web interface working, clients and network added in database, but when user Apple connect to Wi-Fi network - in database wigle.net not added geolocation this hotspot.

**Comment by tailer73** [comment]
Do i understand correctly that if the network has an Apple device, this network shpuld be automatically applied to the map?
