### ISSUE TITLE
Problem parsing SSID's with special characters

### ISSUE THREAD

**Issue by cjunky** [hubert3/iSniff-GPS#7]
Hi,

It seems the app can't handle special characters such as unicode characters in SSID names and crashes when it encounters them:

Traceback (most recent call last):
  File "./iSniff_import.py", line 140, in <module>
    sniff(iface=args.interface, prn=lambda x:process(x), store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 586, in sniff
    r = prn(p)
  File "./iSniff_import.py", line 140, in <lambda>
    sniff(iface=args.interface, prn=lambda x:process(x), store=0)
  File "./iSniff_import.py", line 108, in process
    UpdateDB(clientmac=mac, time=p.time, SSID=p.info)
  File "./iSniff_import.py", line 56, in UpdateDB
    a = AP.objects.get(SSID=SSID)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 143, in get
    return self.get_query_set().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 398, in get
    num = len(clone)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 106, in __len__
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 317, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/util.py", line 41, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 366, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 362, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.DatabaseError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.

cheers

Cj

**Comment by openberkeley** [comment]
Hi! First I want say THANK YOU for your job!

Same here with unreadable SSID's. Monitor mode (mon0 rfmon works ok tho). Sample at http://pastebin.com/F35FdAnL

My setup is:
uname -a
Darwin openbsd.local 12.6.0 Darwin Kernel Version 12.6.0: Wed Dec 17 19:11:40 PST 2014; root:xnu-2050.48.15~1/RELEASE_X86_64 x86_64

**Comment by hubert3** [comment]
Hi @openberkeley, thanks for the report.

Those SSID probes recorded in your paste look weird - 147 or 204 bytes is way too long to be a valid SSID (which should be 32 ASCII characters/bytes, or less characters if using non-ASCII UTF-8 characters as part of the SSID)

It looks to me like a client is broadcasting something weird which Scapy is parsing as an SSID probe, or something is going wrong while sniffing or parsing valid SSID probes

If you can easily repeat this error, any chance you could share a pcap file recorded with airodump-ng containing these probes?

**Comment by openberkeley** [comment]
Hi! Glad to hear from you!

My # tcpdump -I -i en1 -vvv -s 0 says something like:

tsft short preamble bad-fcs
tsft short preamble fragmented bad-fcs
tsft short preamble wep fragmented bad-fcs and so on .. http://pastebin.com/C5bxTCiS
Little 6MB test.pcap itself: http://eoq.kr/056785 

I don't think its a iSniff-GPS problem tho but idk how to drop\reject them packets when program sniff realtime.. Its spams like hell)

**Comment by adam84** [comment]
Why am I getting this email conversation

**Comment by hubert3** [comment]
Hi @openberkeley, please open a new issue and send me a link to a pcap file (not just the console output) that causes crashes if you're still seeing this. Thanks
